blank_issues_enabled: false
contact_links:
  - name: üéôÔ∏è Discussions
    url:  https://github.com/BlackArch/blackarch/discussions
    about: Start a discussion here.
  - name: Matrix
    url:  https://matrix.to/#/#BlackArch:matrix.org
    about: Join our community. Open to all topics, with a strong focus on security and BlackArch.
  - name: Website
    url: https://blackarch.org/index.html
    about: BlackArch official website.
  - name: X
    url: https://x.com/blackarchlinux
    about: Follow us on X! We mainly tweet about new tools, new mirrors, and major project changes.
  - name: Youtube
    url: https://www.youtube.com/channel/UChw5hByy70ey2F7QeLEGICQ
    about: Subscribe to our YouTube channel for tutorials on installation, configuration, and core tool usage.
