# Headers to include with all HTTP request
# header:
#   - 'X-BugBounty-Hacker: h1/pentester'

# Directory based template execution
templates:
  - /usr/share/nuclei-templates/

# Template Filters
# tags: exposures,cve
# author: geeknik,pikpikcu,dhiyaneshdk
# severity: critical,high,medium

# Template Allowlist
# 
# Note: This will take precedence over the .nuclei-ignore file and denylist
# entries (exclude-tags or exclude-templates list).
# include-tags: dos,fuzz # Tag based inclusion
# include-templates: # Template based inclusion
#   - vulnerabilities/xxx
#   - misconfiguration/xxxx

# Template Denylist
# exclude-tags: info # Tag based exclusion
# exclude-templates: # Template based exclusion
#   - vulnerabilities/xxx
#   - misconfiguration/xxxx

# Rate Limit configuration
# rate-limit: 500
# bulk-size: 50
# concurrency: 50

# Init checks
disable-update-check: true
